# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
