# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_like_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Rating'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
