# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170415_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Like',
        ),
    ]
