# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170415_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
