# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='value',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
