# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20170417_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
